/* UI translations only. Accounting records and user labels are not rewritten. */
(() => {
 'use strict';
 const en={
 'Язык':'Language','Обновить':'Refresh','Настройки':'Settings','Свернуть':'Minimize','Обзор':'Overview','Операции':'Transactions','Пояснить PnL':'Explain PnL',
 'Прибыль / убыток проекта':'Project PnL','Стоимость ваших CRH':'Your CRH value','Доход в день':'Daily net income','После указанных расходов':'After configured costs','Окупаемость игры':'Game payback','При сохранении темпа':'At the current rate','Ваша доля':'Your share',
 'CRH в кошельке + награды к выводу + выручка от продаж − покупки CRH − фактический газ. Покупки ПК и апгрейды уже уменьшают баланс токенов и не вычитаются второй раз. Игровое оборудование не оценивается как актив для перепродажи.':'Wallet CRH + claimable rewards + sale proceeds − CRH purchases − actual gas. PCs and upgrades already reduce your token balance and are not deducted again. In-game hardware is not valued as a resale asset.',
 'Из чего складывается PnL':'PnL breakdown','Покупки CRH':'CRH purchases','Средняя цена покупки':'Average purchase price','Продажи / переводы с оценкой':'Sales / valued transfers','Газ по транзакциям':'Transaction gas','Результат продаж токенов':'Realized trading PnL','Токены и награды: переоценка':'Tokens and rewards: unrealized PnL','Курсовой эффект оплат игры':'Token gain on game payments','Расходы в игре':'In-game spending',
 'Результат CRH при оплатах — USD-цена заказа минус себестоимость списанных токенов. Стоимость игровых оплат показана для анализа. PnL учитывает её один раз через уменьшение баланса. Для ETH используется историческая минутная котировка; USDG оценивается по $1. Результат продаж рассчитан по средней себестоимости CRH.':'Token gain on a game payment is the order value in USD minus the cost basis of the spent CRH. Game spending is shown for analysis and counted once through the reduced balance. ETH uses historical minute prices; USDG is valued at $1. Trading PnL uses average CRH cost basis.',
 'Как рассчитан доход и окупаемость':'Income and payback calculation','Награды за 24 часа':'Rewards per 24 hours','Выручка от наград':'Reward value','Электричество в день':'Daily electricity','Резерв на уход + газ в день':'Daily care + gas budget','Комиссия продажи':'Selling fee','Вложения для окупаемости':'Payback investment basis','Ещё вернуть деньгами':'Cash still to recover',
 'Доход в день — награды по текущей котировке минус электричество, комиссия продажи, заданный уход и газ. Это темп за 24 часа, а не обещание завтрашней выплаты. Окупаемость использует базу игровых расходов или вашу ручную сумму; имеющиеся CRH не считаются уже возвращёнными деньгами. Проскальзывание не включено.':'Daily net income is rewards at the current price minus electricity, selling fees, configured care and gas. It is a 24-hour run rate, not a promised payout. Payback uses game spending or your custom investment basis; held CRH is not treated as recovered cash. Slippage is excluded.',
 'Экономика игры и состояние острова':'Game economy and island status','Наш / общий хешрейт':'Your / total hashrate','Бюджет наград сегодня':'Today’s reward budget','Пул на начало дня':'Pool at start of day','Баланс vault в сети':'On-chain vault balance','В кошельке / к выводу':'Wallet / claimable CRH','Добыча / запас энергии':'Mining / energy remaining','Мощность: занято / доступно':'Power: reserved / capacity','Участки / Island Level':'Plots / Island Level','Бонус острова':'Island bonus','Стройка завершится':'Construction finishes',
 'Пул начала дня = бюджет / ставка. Vault включает ещё не выведенные награды. Долларовая оценка использует котировку игры, а не цену продажи всего баланса.':'Start-of-day pool = budget / release rate. The vault includes unclaimed rewards. USD values use the game quote, not the executable sale price of the entire balance.',
 'Показать ещё':'Show more','Только чтение · игра ≈ 1 мин · сеть и история ≈ 2 мин':'Read-only · game ≈ 1 min · chain and history ≈ 2 min',
 'История появится после чтения сети':'Transactions appear after the chain scan','Уточнить $':'Set USD value','Цена неизвестна':'Price unknown','Уточнить операцию':'Review transaction','Подробнее':'Details','Цена при исполнении':'Execution price','Цена в момент запуска':'Price when order was quoted','Не записана':'Not recorded','Себестоимость списанных CRH':'Cost basis of spent CRH','Газ':'Gas','Получено ETH':'ETH received','Потрачено ETH':'ETH spent',
 'USD-сумма и списание CRH подтверждены сетью.':'USD amount and CRH payment are confirmed on-chain.','USD-оценка по ETH/USD начала минуты на Coinbase.':'USD estimate uses the opening ETH/USD price for that minute on Coinbase.','Фактическое количество USDG; долларовая оценка при USDG = $1.':'Actual USDG flow, valued at USDG = $1.','Стоимость уточнена вручную.':'Value was entered manually.','Награды от известного reward vault.':'Rewards from the known reward vault.','Нужно уточнить назначение или стоимость перевода.':'Review the transfer type or its USD value.','Транзакция ↗':'Transaction ↗','Изменить данные':'Edit details',
 'Котировка устарела.':'The price quote is stale.','Показатели острова устарели.':'Island data is stale.','Для дохода подключите этот кошелёк в игре.':'Connect this wallet in the game to see mining income.','Укажите свой кошелёк в настройках или подключите его в игре.':'Set your wallet in Settings or connect it in the game.','Доход показан без резерва на уход.':'Income excludes a care budget.','Баланс не обновлён.':'Balance could not be refreshed.','История не обновлена: ':'History could not be refreshed: ','Читаем историю · ':'Scanning transactions · ','Обновлено ':'Updated ','Последние данные · ':'Last data · ',
 'Оценка без части газа':'Some gas costs are unavailable','Без невыплаченных наград':'Unclaimed rewards excluded','Оценка с токенами и наградами по текущей цене':'Includes tokens and claimable rewards at the current price','Для полного PnL уточните операции':'Review transactions to complete PnL','Восстанавливаем покупки и игровые оплаты':'Rebuilding purchases and game payments','История догоняет текущий баланс':'Transaction history is catching up','Ждём историю операций':'Waiting for transaction history','Уточнить ':'Review ',' операций →':' transactions →',' к выводу':' claimable',' · кошелёк':' · wallet','Возвращено':'Recovered',' дн.':' days','Не окупается':'No payback','Ещё вернуть ':'Still to recover ',' · если темп сохранится':' · if the rate holds','Нужны расходы и ставка начисления':'Needs spending and reward rate','Включена':'Running','Остановлена':'Stopped',' ч':' h','Нет стройки':'No construction','Нет текущей работы':'No active job',' · вся очередь до ':' · queue ends ','Вся очередь до ':'Queue ends ',
 'Цена CRH показана на момент исполнения. Для ETH это историческая оценка. Названия старых заказов можно дополнить; новые фиксируются при открытой игре.':'CRH prices are shown at execution. ETH values use historical estimates. You can label older orders; new orders are captured while the game is open.',
 'CRH Monitor · Панель':'CRH Monitor · Dashboard','Настройки кошелька и расчёта':'Wallet and calculation settings','Кошелёк в Robinhood Chain':'Robinhood Chain wallet','Для показателей острова подключите этот адрес в открытой игре.':'Connect this address in the open game for island data.','База для окупаемости игры, $':'Game payback investment basis, $','Авто: расходы в игре':'Auto: in-game spending','Не влияет на PnL: он считается по транзакциям. Пусто — сумма расходов, показанная игрой.':'Does not affect transaction-based PnL. Leave blank to use the game’s spending total.','Уже возвращено деньгами, $':'Cash already recovered, $','Для срока окупаемости. Только полученные деньги, без оставшихся CRH.':'For payback only. Enter recovered cash, excluding held CRH.','Комиссия продажи, %':'Selling fee, %','Для дохода в день. Значение 3% — допущение; проскальзывание не включено.':'Used for daily income. The default 3% is an assumption; slippage is excluded.','Уход за ПК, $/день':'PC care, $/day','Не задан':'Not set','Средний расход на пасту, чистку и ремонт. Пусто — доход без ухода.':'Average paste, cleaning and repair cost. Blank means care is excluded.','Газ, $/день':'Gas budget, $/day','Резерв для дохода в день. PnL использует фактический газ операций с CRH.':'Daily income budget. PnL uses actual gas for CRH transactions.','Панель поверх игры':'Show the in-game overlay','Сохранить':'Save','Открыть игру ↗':'Open game ↗','Открыть игру':'Open game','Экспорт истории':'Export history','Полная панель и настройки ↗':'Dashboard and settings ↗',
 'Данные хранятся в этом браузере. Расширение читает игру и сеть; управление кошельком остаётся в игре.':'Data stays in this browser profile. The extension reads the game and chain; wallet actions stay in the game.','Закрыть':'Close','Назначение':'Transaction type','Название':'Label','Например, Seed или Plot 2':'For example, Seed or Plot 2','Стоимость операции, $':'Transaction value, $','Не определена':'Unknown','Газ операции, $':'Transaction gas, $','Не определён':'Unknown','Сбросить уточнения':'Reset corrections',
 'Сохраняю…':'Saving…','Сохранено':'Saved','Сохранено; сеть сейчас недоступна':'Saved; network is currently unavailable','Не удалось сохранить':'Could not save','Покупка CRH':'CRH purchase','Награды / безвозмездное получение':'Rewards / gift','Неизвестный входящий перевод':'Unknown incoming transfer','Оплата в игре':'Game payment','Продажа CRH':'CRH sale','Перевод с учётом стоимости вне этого кошелька':'Transfer with value recovered outside this wallet','Неизвестный исходящий перевод':'Unknown outgoing transfer',
 'USD-сумма оплаты подтверждена сетью. Можно уточнить название покупки.':'The payment’s USD value is confirmed on-chain. You can edit its label.','Укажите фактическую USD-стоимость. Награды имеют нулевую себестоимость. Входящий перевод между своими кошельками требует стоимости приобретения, а не текущего курса.':'Enter the actual USD value. Rewards have zero cost basis. Transfers between your own wallets need their original acquisition cost, not the current market price.','Укажите стоимость операции':'Enter the transaction value','Не удалось сбросить':'Could not reset',
 'Покупка ПК':'PC purchase','Новый участок':'New plot','Апгрейд мощности':'Power upgrade','Стройка / апгрейд':'Construction / upgrade','Электричество':'Electricity','Термопаста':'Thermal paste','Ремонт':'Repair','Обслуживание':'Maintenance','Комплектующие':'Components','Покупка в магазине':'Shop purchase','Покупка в игре':'Game purchase','Входящий перевод':'Incoming transfer','Исходящий перевод':'Outgoing transfer','Вывод наград':'Reward claim',
 'CRH Monitor обновлён · перезагрузить игру':'CRH Monitor updated · reload game','После обновления расширения вкладку игры нужно перезагрузить':'Reload the game tab after updating the extension',
 'RPC не вернул корректный ответ':'RPC returned an invalid response','RPC вернул другую сеть':'RPC returned the wrong chain','Нет исторического курса':'Historical price unavailable','RPC не вернул журнал CRH':'RPC returned invalid CRH logs','Транзакция ещё не доступна':'Transaction is not available yet'
 };
 Object.assign(en,{
  "Изначальный инвест": "Initial investment",
  "Инвест + реинвест": "Investment + reinvestment",
  "Включая электричество, уход и остальные оплаты игры": "Includes electricity, care and all other game payments",
  "Реинвест и цены клеймов": "Reinvestment and claim prices",
  "Реинвестировано наград": "Rewards reinvested",
  "Из них: известные энергия и уход": "Identified electricity and care",
  "Эти награды по цене клейма": "Those rewards at claim prices",
  "Курс: клейм → оплата": "Price change: claim → payment",
  "Все клеймы по цене получения": "All claims at receipt prices",
  "Результат до реинвеста": "Result before reinvestment",
  "Изначальный инвест — покупки CRH за внешние деньги, включая пополнения. Инвест + реинвест добавляет долю наград во всех игровых оплатах: ПК, стройка, энергия, уход и прочее. Смешанный баланс распределяется пропорционально. Результат до реинвеста = Project PnL + потраченные на игру награды; это учётный показатель до этих расходов, не деньги к выводу и не стоимость оборудования.": "Initial investment is external money spent buying CRH, including top-ups. Investment + reinvestment adds the reward-funded share of all game payments: PCs, construction, energy, care and more. Mixed balances are allocated proportionally. Result before reinvestment = Project PnL + rewards spent in the game; this is an accounting result before those expenses, not withdrawable cash or hardware value.",
  "Цена CRH при клейме": "CRH price at claim",
  "Оценка полученных наград": "Claimed reward value",
  "Источник цены": "Price source",
  "Отклонение времени котировки": "Quote time offset",
  " с": " s",
  "Оплачено из наград (оценка)": "Reward-funded payment (estimate)",
  "Уточнена вручную": "Entered manually",
  "Котировка игры рядом с клеймом (оценка)": "Game quote near claim (estimate)",
  "Ближайшая игровая оплата (оценка)": "Nearby game payment (estimate)",
  "Dexscreener рядом с клеймом (оценка)": "Dexscreener near claim (estimate)",
  "Нет исторической цены для ": "Historical prices missing for ",
  " клеймов. Сумма реинвеста известна из оплат; курсовой эффект доступен только при сохранённых ценах. ": " claims. Reinvestment value is known from payments; price-change effects require saved claim prices. ",
  "Известная оценка клеймов: ": "Known claim value: ",
  "Цены клеймов — оценки по ближайшей котировке в пределах 60 секунд. Источник и время показаны в операциях; сегодняшний курс не подставляется в прошлое.": "Claim prices are estimates from the nearest quote within 60 seconds. Source and timing appear in Transactions; current prices are never applied to the past.",
  "Цена CRH при клейме, $": "CRH price at claim, $",
  "Заполняется автоматически из сохранённой котировки рядом с клеймом. Вручную — только уточнение; себестоимость наград для Project PnL остаётся нулевой.": "Filled automatically from a saved quote near the claim. Manual input is only a correction; reward acquisition cost for Project PnL stays zero."
});
 Object.assign(en,{
  " CRH в кошельке + ":" wallet CRH + ",
  " · снимок ":" · snapshot ",
  " · синхронизация":" · syncing",
  "Только чтение · игра ≈ 15 с · баланс ≈ 30 с":"Read only · game ≈ 15s · wallet ≈ 30s"
 });
 Object.assign(en,{
  "Энергия и уход / день":"Energy and care / day","При непрерывной добыче":"With continuous mining","После энергии, Care и удержаний":"After energy, care and deductions",
  "Доход и расходы за 24 часа":"24-hour income and costs","Налог на claim":"Claim tax","Уход и ремонт / день":"Care and repairs / day","Резерв на газ / день":"Daily gas budget","Care всех ПК сейчас":"Care all PCs now",
  "Уход за ПК":"PC care","Уход за всеми ПК":"Care all PCs","Разгон ПК":"PC overclock",
  "Для чистого дохода не хватает данных о стоимости ухода.":"Care cost data is missing for net income."," Rewards после налога":" Rewards after tax"," · налог claim оценён в 10%":" · claim tax estimated at 10%"," · оценка":" · estimate",
  "Темп за 24 часа при текущих цене, хеше и бюджете. Энергия предполагает пополнение; будущие награды не гарантированы.":"A 24-hour run rate at the current price, hash and reward budget. Energy assumes refills; future rewards are not guaranteed.",
  "Уход задан вручную и заменяет автоматический резерв.":"Manual care replaces the automatic budget.","Суточный уход получен от игры.":"Daily care cost comes from the game.",
  "Уход оценён по заработку до реферального удержания: ":"Care is estimated from earnings before referral withholding: ",
  "%. Все три вида ухода уже включены; повторно починка не вычитается. Минимум Care учтён для общего платежа раз в 6 часов. Между обслуживаниями H/s может снижаться.":"%. All three care types are included; repairs are not deducted again. The Care minimum assumes a combined payment every 6 hours. Hash can fall between care payments.",
  "Ставка claim tax не получена от игры: заложены максимальные 10% из Docs. В настройках можно указать фактическую ставку, в том числе 0%.":"The game has not supplied claim tax: the maximum documented 10% is used. Settings can override it with the actual rate, including 0%.",
  "Активный разгон ускоряет износ; после его окончания темп добычи изменится.":"An active overclock speeds up wear; mining income changes when it expires.",
  "Следующая ставка выдачи пула: ":"Next pool release rate: ",". После смены дня доход пересчитается по новому бюджету.":". Income is recalculated from the new budget after rollover.",
  "Комиссия продажи — заданное допущение; проскальзывание не включено. Газ вычитается в размере указанного резерва.":"Selling fees use your configured assumption; slippage is excluded. Gas uses the configured daily budget.",
  "Авто: процент заработка":"Auto: share of earnings","Пусто — автоматический резерв по новым правилам Care. Введённая сумма заменяет его, а не добавляется сверху.":"Blank uses the new Care rules. A manual amount replaces that budget instead of being added to it.",
  "Налог на claim, %":"Claim tax, %","Авто: игра или 10%":"Auto: game or 10%","Пусто — ставка из игры; если она недоступна, оценка по максимальным 10% из Docs. Для первого дня можно указать 0%.":"Blank uses the game rate, falling back to the documented maximum of 10%. First-day accounts can set 0%."
 });
 Object.assign(en,{
  "Окупаемость и ROI":"Payback and ROI","Внешний инвест":"External investment","Вернулось продажами, за вычетом газа":"Sales returned, net of gas",
  "Окуплено":"Recovered","Окуп: —":"Payback: —","Окуп: ≈ ":"Payback: ≈ "," дн.":" days",
  "Внешний инвест — реальные деньги на покупки CRH из истории кошелька. Окуп — ещё не возвращённая продажами сумма / чистый доход в день. ROI = (стоимость CRH и Rewards после налога + продажи − газ − выбранная сумма инвеста) / выбранная сумма инвеста. Переводы между кошельками не считаются продажами. Срок рассчитан по текущему темпу; реинвест и изменения игры его изменят.":"External investment is real money spent buying CRH in the wallet history. Payback is the amount still to recover through sales divided by daily net income. ROI = (wallet CRH and net Rewards value + sales - gas - the selected investment amount) / the selected investment amount. Wallet transfers are not sales. The payback uses the current run rate; reinvestment and game changes will alter it."
 });
 const reverse=Object.fromEntries(Object.entries(en).map(([ru,value])=>[value,ru]));
 function language(settings){if(settings?.language==='ru'||settings?.language==='en')return settings.language;return /^ru\b/i.test(globalThis.navigator?.language||'en')?'ru':'en'}
 const locale=lang=>lang==='ru'?'ru-RU':'en-US';
 function t(key,lang){const ru=Object.hasOwn(en,key)?key:reverse[key]??key;return lang==='ru'?ru:en[ru]??key}
 const fmt=(n,d=2,lang='en')=>n===null||n===undefined||!Number.isFinite(n)?'—':new Intl.NumberFormat(locale(lang),{maximumFractionDigits:d}).format(n);
 const usd=(n,d,lang='en')=>n===null||n===undefined||!Number.isFinite(n)?'—':'$'+(d===undefined&&(n===0||Math.abs(n)>=.01)?new Intl.NumberFormat(locale(lang),{minimumFractionDigits:2,maximumFractionDigits:2}).format(n):fmt(n,d??6,lang));
 function label(record,lang){if(record.labelIsCustom)return record.label;const s=record.label||'';if(/^ПК /.test(s))return(lang==='ru'?'ПК ':'PC ')+s.slice(3);for(const prefix of ['Новый участок','Апгрейд мощности'])if(s.startsWith(prefix))return t(prefix,lang)+s.slice(prefix.length);return t(s,lang)}
 function bind(root){
  const texts=[],attrs=[],walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);
  while(walker.nextNode()){const node=walker.currentNode,key=node.textContent.trim();if(Object.hasOwn(en,key))texts.push({node,key,original:node.textContent});}
  for(const node of root.querySelectorAll('[aria-label],[placeholder],[title]'))for(const attr of ['aria-label','placeholder','title']){const key=node.getAttribute(attr);if(Object.hasOwn(en,key))attrs.push({node,attr,key});}
  return lang=>{for(const{node,key,original}of texts)node.textContent=original.replace(key,t(key,lang));for(const{node,attr,key}of attrs)node.setAttribute(attr,t(key,lang));};
 }
 const api={en,language,locale,t,fmt,usd,label,bind};globalThis.CRHI18n=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})();
