/* Read-only tooltips in the game's own leaderboard; matches rank and public name. */
(() => {"use strict";let stopped=false,host=null,tip=null,data={},native={};const C=CRHMonitor,P=CRHProject,I=CRHI18n;
 const active=()=>{try{return !!chrome.runtime.id}catch{return false}};
 function stop(){if(stopped)return;stopped=true;document.removeEventListener('pointerover',over);document.removeEventListener('pointerout',out);document.removeEventListener('focusin',over);document.removeEventListener('focusout',out);window.removeEventListener('message',message);try{chrome.storage.onChanged.removeListener(changed)}catch{}host?.remove();}
 function hide(){if(tip)tip.hidden=true;}
 function message(e){if(e.source!==window||e.origin!==location.origin||e.data?.type!=='CRH_MONITOR_PROJECT_V1'||e.data.kind!=='board')return;const b=P.validateBoard(e.data.payload);if(b)native[b.board]=b;}
 function changed(changes,area){if(area==='local')for(const[k,v]of Object.entries(changes))data[k]=v.newValue;}
 function over(e){if(stopped)return;if(!active()){stop();return;}const row=e.target?.closest?.('#island-leaderboard .island-board-row[data-rank]');if(!row)return;const panel=row.closest('#island-leaderboard'),kind=panel?.dataset.board==='spend'?'spend':'hash',b=native[kind];if(!b)return;const name=row.querySelector('.island-board-name')?.textContent?.trim(),r=b.rows.find(r=>String(r.rank)===row.dataset.rank&&(r.owner||r.name||'Islander')===name);if(!r)return;
 if(!host){host=document.createElement('div');host.id='crh-monitor-leader-tooltip';host.style.cssText='position:fixed;z-index:2147483647;pointer-events:none';const shadow=host.attachShadow({mode:'open'});tip=document.createElement('div');tip.style.cssText='padding:13px 16px;border:1px solid #477661;border-radius:12px;background:#11251e;color:#d7f0e4;white-space:pre-line;font:12px/1.6 system-ui;box-shadow:0 8px 30px #0008;box-sizing:border-box';shadow.append(tip);document.body.append(host);}
 const lang=I.language(C.cleanSettings(data.settings)),p=P.clean(data.project),price=data.market&&Date.now()-data.market.seenAt<120000?data.market.priceUSD:null;tip.textContent=CRHProjectView.playerText(r,{...b,priceUSD:price},p,lang);tip.hidden=false;const rect=row.getBoundingClientRect(),width=Math.min(360,innerWidth-24);host.style.width=width+'px';host.style.left=Math.max(12,Math.min(innerWidth-width-12,rect.left))+'px';host.style.top=Math.max(12,Math.min(innerHeight-tip.offsetHeight-12,rect.bottom+6))+'px';}
 function out(e){const row=e.target?.closest?.('#island-leaderboard .island-board-row[data-rank]');if(row&&!row.contains(e.relatedTarget))hide();}
 window.addEventListener('message',message);document.addEventListener('pointerover',over);document.addEventListener('pointerout',out);document.addEventListener('focusin',over);document.addEventListener('focusout',out);try{chrome.storage.onChanged.addListener(changed);chrome.storage.local.get(['settings','project','market']).then(x=>{data=x}).catch(()=>{if(!active())stop()})}catch{stop()}
})();
