/* UI for project observations. Public names are always inserted as text. */
(() => {"use strict";const P=CRHProject,I=CRHI18n;
 const words={
 'Проект':'Project','Динамика проекта':'Project dynamics','Общий хешрейт':'Total hashrate','Цена CRH':'CRH price','Награды в сутки':'Daily rewards','Пул':'Pool','Vault':'Vault','24 ч':'24h','7 дней':'7d','30 дней':'30d','Показатель':'Metric','Период':'Period','Нет наблюдений. Откройте игру с активной сессией.':'No observations yet. Open the game with an active session.','С начала наблюдений':'Since observations began','За выбранный период':'Over selected period','Точки на графике — реальные наблюдения. Пропуски не восстанавливаются.':'Chart points are recorded observations. Missing periods are not reconstructed.','Лидерборды':'Leaderboards','Хешрейт':'Hashrate','Top Spenders':'Top Spenders','Последний снимок':'Latest snapshot','Снимок':'Snapshot','Нет снимков. Дождитесь чтения лидерборда из игры.':'No snapshots yet. Wait for the leaderboard read from the game.','В рейтинге':'Ranked islands','Игрок':'Player','История изменений':'Changes','Правила экономики изменились':'Economy rules changed','Бюджет наград изменился':'Reward budget changed','Резкое изменение хешрейта':'Large hashrate change','Резкое изменение цены':'Large price change','Снимков':'Snapshots','Наблюдения':'Observations','Экспорт динамики':'Export project history','Экономика каждые 10 мин, до 30 дней. Топ-100 обоих рейтингов раз в час, до 14 дней с ограничением объёма. Нужна открытая игра.':'Economy every 10 minutes, up to 30 days. Both top-100 boards hourly, up to 14 days within the storage cap. Requires an open game.','Сервер пометил рейтинг устаревшим.':'The server marked this board as stale.','Неполный снимок':'Partial snapshot','Источник сейчас недоступен':'Source currently unavailable','Игровые расходы':'In-game spending','Потрачено CRH':'CRH spent','Оценка этих CRH по курсу снимка':'These CRH valued at the snapshot price','Историческая USD-сумма не предоставлена API.':'The API does not provide historical USD spending.','Эквивалент готовых ПК':'Ready-PC equivalent','По последнему каталогу':'Latest observed catalog','Бонус 0–84%, снижение скорости до 50%. Сборки из деталей могут быть дешевле. Это не внесённые деньги.':'Assumes 0–84% bonus and up to 50% speed loss. Custom builds may be cheaper. This is not cash invested.','Для оценки нужен свежий ответ магазина с ценами ПК.':'A PC catalog response is needed for this estimate.','Island Level':'Island Level','Точность по одному H/s ограничена: разные сборки дают разную стоимость.':'H/s alone cannot determine exact spending: build costs differ.','Изменение места':'Rank change','Нет прежнего снимка':'No previous snapshot','Сохранённые снимки':'Saved snapshots','Значение':'Value','По наблюдениям':'Observed data','Просмотр острова':'View island','Данные':'Data','Сумма CRH не равна внесённым долларам.':'Spent CRH is not the same as dollars invested.'};
 const t=(s,lang)=>lang==='en'?(words[s]??s):s;
 const when=(at,lang)=>at?new Date(at).toLocaleString(I.locale(lang),{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';
 function playerText(row,board,project,lang){const fmt=(n,d)=>I.fmt(n,d,lang),usd=(n,d)=>I.usd(n,d,lang),v=P.playerValue(row,board?.priceUSD,project.catalog?.cards||[]),lines=[(row.owner||row.name||'Islander')+' · #'+fmt(row.rank,0),fmt(row.hash,2)+' H/s'];
 if(v.spentUSD!==null)lines.push(t('Игровые расходы',lang)+': '+usd(v.spentUSD));
 if(v.spentTokens!==null){lines.push(t('Потрачено CRH',lang)+': '+fmt(v.spentTokens,2));if(v.tokenValueUSD!==null)lines.push(t('Оценка этих CRH по курсу снимка',lang)+': '+usd(v.tokenValueUSD));}
 if(v.spentUSD===null)lines.push(t('Историческая USD-сумма не предоставлена API.',lang));
 if(v.hardwareLow!==null){lines.push(t('Эквивалент готовых ПК',lang)+': '+usd(v.hardwareLow)+' – '+usd(v.hardwareHigh));lines.push(t('По последнему каталогу',lang)+': '+usd(v.ratioLow,2)+' – '+usd(v.ratioHigh,2)+' / H/s');lines.push(t('Бонус 0–84%, снижение скорости до 50%. Сборки из деталей могут быть дешевле. Это не внесённые деньги.',lang));}else lines.push(t('Для оценки нужен свежий ответ магазина с ценами ПК.',lang));
 return lines.join('\n');}
 const css=`.project-controls{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:18px}.project-controls select{width:auto;max-width:100%;background:#182638;color:#c4d3e7;border:1px solid #34445b;border-radius:8px;padding:7px;font:12px system-ui}.project-kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin:14px 0 20px}.project-kpis strong{font-size:20px;font-weight:650;display:block;margin:5px 0}.project-kpis small{font-size:11px}.project-kpis .caption{font-size:11px}.project-chart{width:100%;height:165px;display:block;background:#0c1420;border:1px solid #273549;border-radius:12px}.project-chart text{fill:#8fa4bd;font:10px system-ui}.project-chart path{stroke:#83e2bb;stroke-width:2;fill:none;stroke-linecap:round;stroke-linejoin:round}.project-heading{font-size:13px;font-weight:600;margin:22px 0 12px;color:#dce8f6}.project-board{max-height:400px;overflow:auto;scrollbar-width:thin;margin-top:12px}.project-player{display:grid;grid-template-columns:32px minmax(0,1fr) auto;gap:10px;width:100%;padding:11px 4px;text-align:left;border:0;border-bottom:1px solid #273549;border-radius:0;background:none;color:#dce8f6;align-items:center;font-size:12px}.project-player span:nth-child(2){overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.project-player small{color:#8fa4bd}.project-player:hover,.project-player:focus-visible{background:#1a2c38}.project-status{font-size:11px;color:#8fa4bd;margin:8px 0}.project-tip{position:fixed;max-width:360px;padding:13px 16px;border:1px solid #477661;border-radius:12px;background:#11251e;color:#d7f0e4;z-index:2147483647;white-space:pre-line;font:12px/1.6 system-ui;box-shadow:0 8px 30px #0008;pointer-events:none}.project-event{font-size:11px;padding:7px 0;color:#a5b4c8;border-bottom:1px solid #273549}.project-empty{font-size:12px;color:#8fa4bd;padding:25px 0}.compact .project-kpis{grid-template-columns:1fr;gap:7px}.compact .project-kpis>div{display:flex;align-items:baseline;gap:10px;flex-wrap:wrap}.compact .project-kpis strong{font-size:17px;margin:0}.compact .project-chart{height:140px}.project-export{margin-top:16px}`;
 function attach(panel){const style=document.createElement('style');style.textContent=css;panel.append(style);const tab=document.createElement('button');tab.className='tab';tab.dataset.tab='project';tab.setAttribute('role','tab');tab.setAttribute('aria-selected','false');tab.textContent='Проект';panel.querySelector('.tabs').append(tab);const root=document.createElement('div');root.dataset.panel='project';root.hidden=true;panel.querySelector('.footer').before(root);
 let lastData=null,lang='ru',hours=24,metric='totalHash',kind='hash',snapshot='latest',lastKey='';
 const tip=document.createElement('div');tip.className='project-tip';tip.hidden=true;panel.append(tip);
 const node=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e};
 function selector(options,value,label,onChange){const s=node('select');s.setAttribute('aria-label',t(label,lang));for(const[v,name]of options){const o=node('option',null,t(name,lang));o.value=v;s.append(o)}s.value=String(value);s.addEventListener('change',()=>{onChange(s.value);lastKey='';render(lastData)});return s;}
 function render(data){if(!data)return;lastData=data;lang=I.language(CRHMonitor.cleanSettings(data.settings));tab.textContent=t('Проект',lang);const p=P.clean(data.project),key=JSON.stringify([lang,hours,metric,kind,snapshot,p.economy.at(-1)?.at,p.latest.hash?.seenAt,p.latest.spend?.seenAt,p.catalog?.seenAt,p.errors]);if(key===lastKey)return;lastKey=key;tip.hidden=true;root.replaceChildren();const fmt=(n,d)=>I.fmt(n,d,lang),usd=(n,d)=>I.usd(n,d,lang),label=s=>t(s,lang);
 const controls=node('div','project-controls');controls.append(selector([[24,'24 ч'],[168,'7 дней'],[720,'30 дней']],hours,'Период',v=>hours=Number(v)),selector([['totalHash','Общий хешрейт'],['priceUSD','Цена CRH'],['budgetCRH','Награды в сутки'],['poolCRH','Пул'],['vaultCRH','Vault']],metric,'Показатель',v=>metric=v));root.append(controls);
 const cards=node('div','project-kpis');for(const[field,title,isUSD]of [['totalHash','Общий хешрейт',false],['priceUSD','Цена CRH',true],['budgetCRH','Награды в сутки',false]]){const d=P.delta(p.economy,field,hours),box=node('div');box.append(node('div','caption',label(title)),node('strong',null,isUSD?usd(d?.current,8):fmt(d?.current,0)+(field==='totalHash'?' H/s':' CRH')),node('small',d?.pct>0?'positive':d?.pct<0?'negative':'muted',d?.pct!==null&&d?.pct!==undefined?(d.pct>0?'+':'')+fmt(d.pct,1)+'% · '+label(d.fullWindow?'За выбранный период':'С начала наблюдений'):'—'));cards.append(box)}root.append(cards);
 const points=p.economy.filter(e=>e.at>=Date.now()-hours*3600000&&e[metric]!==null&&e[metric]!==undefined);const NS='http://www.w3.org/2000/svg',svg=document.createElementNS(NS,'svg');svg.classList.add('project-chart');svg.setAttribute('viewBox','0 0 520 170');svg.setAttribute('role','img');svg.setAttribute('aria-label',label('Динамика проекта'));
 if(points.length){const vals=points.map(e=>e[metric]),lo=Math.min(...vals),hi=Math.max(...vals),span=Math.max(1,points.at(-1).at-points[0].at),range=hi-lo||Math.max(hi*.01,1),x=e=>50+(e.at-points[0].at)/span*450,y=e=>130-(e[metric]-lo)/range*100;const line=document.createElementNS(NS,'path');line.setAttribute('d',points.map((e,i)=>(i&&e.at-points[i-1].at<=3*P.ECON_INTERVAL?'L':'M')+x(e).toFixed(2)+' '+y(e).toFixed(2)).join(' '));svg.append(line);for(const e of points.filter((_,i)=>i%Math.max(1,Math.ceil(points.length/200))===0)){const c=document.createElementNS(NS,'circle');c.setAttribute('cx',x(e));c.setAttribute('cy',y(e));c.setAttribute('r','2');c.setAttribute('fill','#83e2bb');const title=document.createElementNS(NS,'title');title.textContent=when(e.at,lang)+' · '+(metric==='priceUSD'?usd(e[metric],8):fmt(e[metric],2));c.append(title);svg.append(c)}for(const[yVal,val]of [[30,hi],[130,lo]]){const tx=document.createElementNS(NS,'text');tx.setAttribute('x','7');tx.setAttribute('y',yVal);tx.textContent=metric==='priceUSD'?usd(val,5):fmt(val>=1000000?val/1000000:val,1)+(val>=1000000?'M':'');svg.append(tx)}root.append(svg,node('div','project-status',when(points[0].at,lang)+' → '+when(points.at(-1).at,lang)+' · '+label('Наблюдения')+': '+points.length));}else root.append(node('div','project-empty',label('Нет наблюдений. Откройте игру с активной сессией.')));
 root.append(node('p','explain',label('Точки на графике — реальные наблюдения. Пропуски не восстанавливаются.')));
 root.append(node('div','project-heading',label('Лидерборды')));const boardControls=node('div','project-controls'),history=p.boards[kind],options=[['latest','Последний снимок'],...history.slice().reverse().map(b=>[String(b.seenAt),when(b.seenAt,lang)])];if(snapshot!=='latest'&&!history.some(b=>String(b.seenAt)===snapshot))snapshot='latest';boardControls.append(selector([['hash','Хешрейт'],['spend','Top Spenders']],kind,'Лидерборды',v=>{kind=v;snapshot='latest'}),selector(options,snapshot,'Снимок',v=>snapshot=v));root.append(boardControls);
 const b=snapshot==='latest'?p.latest[kind]:P.unpackBoard(p,history.find(e=>String(e.seenAt)===snapshot));
 if(b){root.append(node('div','project-status',label('Снимок')+': '+when(b.asOf??b.seenAt,lang)+' · '+label('В рейтинге')+': '+fmt(b.ranked,0)+' · Top '+b.rows.length));if(b.stale||!b.complete)root.append(node('p','note',label(b.stale?'Сервер пометил рейтинг устаревшим.':'Неполный снимок')));const list=node('div','project-board');
 for(const r of b.rows){const button=node('button','project-player');button.type='button';button.append(node('small',null,'#'+fmt(r.rank,0)),node('span',null,r.owner||r.name||'Islander'),node('span',null,kind==='spend'?fmt(r.spentTokens,0)+' CRH':fmt(r.hash,1)+' H/s'));const info=playerText(r,b,p,lang);button.title=info;const show=()=>{tip.textContent=info;tip.hidden=false;const box=button.getBoundingClientRect(),width=Math.min(360,innerWidth-24);tip.style.width=width+'px';tip.style.left=Math.max(12,Math.min(innerWidth-width-12,box.left))+'px';tip.style.top=Math.max(12,Math.min(innerHeight-tip.offsetHeight-12,box.bottom+6))+'px'};button.addEventListener('pointerenter',show);button.addEventListener('focus',show);button.addEventListener('click',show);button.addEventListener('pointerleave',()=>tip.hidden=true);button.addEventListener('blur',()=>tip.hidden=true);list.append(button)}root.append(list);root.append(node('p','explain',label('Сумма CRH не равна внесённым долларам.')));}else root.append(node('div','project-empty',label('Нет снимков. Дождитесь чтения лидерборда из игры.')));
 if(p.errors[kind])root.append(node('p','explain',label('Источник сейчас недоступен')+' · HTTP '+(p.errors[kind].status||'—')));
 if(p.events.length){root.append(node('div','project-heading',label('История изменений')));for(const e of p.events.slice(-5).reverse()){const name={rules:'Правила экономики изменились',budget:'Бюджет наград изменился',hash:'Резкое изменение хешрейта',price:'Резкое изменение цены'}[e.type];const line=when(e.at,lang)+' · '+label(name||'Данные')+(e.type!=='rules'?' · '+(e.type==='price'?usd(e.before,6)+' → '+usd(e.after,6):fmt(e.before,0)+' → '+fmt(e.after,0)):'');root.append(node('div','project-event',line));}}
 const exportButton=node('button','project-export',label('Экспорт динамики'));exportButton.addEventListener('click',()=>P.download(lastData.project));root.append(exportButton,node('p','explain',label('Экономика каждые 10 мин, до 30 дней. Топ-100 обоих рейтингов раз в час, до 14 дней с ограничением объёма. Нужна открытая игра.')));
 }
 return{render};
 }
 globalThis.CRHProjectView={attach,playerText};
})();
