const test=require('node:test'),assert=require('node:assert/strict'),C=require('../shared.js'),P=require('../project.js'),B=require('../planner.js'),A=require('../analytics.js');
const now=Date.now(),w='0x'+'2'.repeat(40),q=n=>(BigInt(n)*10n**18n).toString();
function fixture(){const parts=[{id:'cpu1',kind:'cpu',name:'CPU',usd:1,quantity:1},{id:'gpu1',kind:'gpu',name:'GPU',usd:5,quantity:1},{id:'case1',kind:'case',name:'Case',usd:1,quantity:1}],card={id:'seed',name:'Seed',hash:10,usd:20,watts:50,minHall:1,limit:1,includedHours:24,recipe:parts};const level=(level,extra={})=>({level,minutes:15,baseUSD:2,perHashUSD:.01,minHall:1,minPlots:1,bonusPct:0,hashCap:200,capacityW:null,...extra});const game={wallet:w,seenAt:now,serverNow:now,settledAt:now,priceUSD:.01,priceQuotable:true,rateConfirmed:true,settlement:'ready',myHash:10,totalHash:1000,hourlyWei:q(250),budgetWei:q(600000),powerLevel:0,gridCapacity:60,gridReserved:50,energyHours:0,energyKwh:0,electricityUSD:.55,watts:50,hall:1,openPlots:1,hashRecord:10,packageLimits:[{id:'seed',owned:1,max:1}],pcs:[{id:'setup_1',ready:true,running:true,hash:10,watts:50,thermalLossPct:0,wearLossPct:0}],items:parts.map((p,i)=>({id:'part'+i,catalog:p.id,installedSetup:'setup_1'})),construction:{plots:[level(1),level(2)],hall:[level(1),level(2,{minPlots:2,bonusPct:6})],power:[level(0,{capacityW:60}),level(1,{capacityW:150})]}};return{settings:{...C.defaults(),wallet:w,language:'en',positions:{}},games:{[w]:game},market:game,project:{catalog:{seenAt:now,cards:[card]}}};}
test('planner respects budgets, live grid gates, card limits and supplies an exact parts route',()=>{const d=fixture(),r=B.plan(d,{budget:120,days:2,hashDailyPct:0,budgetDailyPct:0},now);assert(!r.error);assert(r.plans.length);assert(r.plans.every(p=>p.estimate.spend<=120+1e-8));for(const p of r.plans){assert(p.estimate.watts<=d.games[w].construction.power.find(l=>l.level===p.power).capacityW);assert(!p.actions.some(a=>a.type==='pc'&&a.mode==='ready'));}assert(r.plans.some(p=>p.actions.some(a=>a.type==='pc'&&a.mode==='parts')));assert(r.plans[0].estimate.hash>10);});
test('low mining reward favors no purchase or shutdown rather than spending the whole budget',()=>{const d=fixture();d.games[w].budgetWei=q(1);d.games[w].hourlyWei='0';const r=B.plan(d,{budget:100,days:10,hashDailyPct:0,budgetDailyPct:0},now);assert(!r.error);assert.equal(r.plans[0].capital,0);assert(!r.plans[0].actions.some(a=>a.type==='pc'));});
test('included energy never pays for care and small operating budgets are rejected',()=>{const d=fixture();d.games[w].energyKwh=100000;const r=B.plan(d,{budget:0,days:10},now);assert.equal(r.error,'operating-budget');assert(r.required>0);});
test('stale or incomplete data never yields a pretend optimum',()=>{const d=fixture();assert.equal(B.plan(d,{},now+120001).error,'fresh-data');delete d.games[w].construction;assert.equal(B.plan(d,{},now).error,'fresh-data');});
test('scenario inputs are bounded and builder price grows with historical hash',()=>{assert.equal(B.options({days:999,hashDailyPct:-100}).days,30);assert.equal(B.options({hashDailyPct:-100}).hashDailyPct,-50);assert.equal(B.jobPrice({baseUSD:5,perHashUSD:.01},111),6.11);});
test('personal growth and project dilution are separated; gaps cannot create false activity spikes',()=>{const d=fixture();d.games[w].seenAt=now;d.games[w].myHash=20;d.games[w].totalHash=200;d.history=[{wallet:w,at:now-3600000,myHash:10,totalHash:100}];d.project.economy=[{at:now-3600000,totalHash:100},{at:now,totalHash:200}];const r=A.summary(d,24,now);assert.equal(r.share,.1);assert.equal(r.sharePoints,0);assert.equal(r.dilutionPct,50);assert.equal(r.spikes.length,0);});
test('ranked islands and new top-100 entries are not mislabeled as new humans',()=>{let p=P.saveBoard(null,{board:'hash',page:1,query:'',seenAt:now-3600000,asOf:now-3600000,complete:true,stale:false,ranked:120,rows:[{id:'isl_'+'1'.repeat(20),rank:1,hash:10}]});p=P.saveBoard(p,{board:'hash',page:1,query:'',seenAt:now,asOf:now,complete:true,stale:false,ranked:130,rows:[{id:'isl_'+'2'.repeat(20),rank:1,hash:20}]});const r=A.summary({settings:{wallet:w},project:p},24,now);assert.equal(r.ranked,130);assert.equal(r.rankedDelta,10);assert.equal(r.newcomers,1);});

test('account history migrates legacy observations and remains wallet scoped',()=>{const raw={},s={wallet:w,seenAt:now,myHash:20,totalHash:100};const a=A.save(raw,s,[{wallet:w,at:now-3600000,myHash:10,totalHash:100},{wallet:'0x'+'3'.repeat(40),at:now-1800000,myHash:999,totalHash:100}]);assert.equal(a[w].length,2);assert.equal(a[w][0].share,.1);assert.deepEqual(raw,{});});

test('a new island may start with the observed one-dollar Grain card instead of a hard-coded 25 dollar minimum',()=>{const d=fixture(),g=d.games[w];g.pcs=[];g.items=[];g.myHash=0;g.hourlyWei='0';g.hashRecord=0;g.watts=0;g.gridReserved=0;g.packageLimits=[{id:'grain',owned:0,max:1}];d.project.catalog.cards=[{id:'grain',name:'Grain',hash:.25,usd:1,watts:5,minHall:1,limit:1,includedHours:24,recipe:[{id:'system_grain',name:'Grain',kind:'system',usd:1,quantity:1}]}];const r=B.plan(d,{budget:3,days:2,hashDailyPct:0,budgetDailyPct:0},now);assert(!r.error);assert(r.plans.some(p=>p.actions.some(a=>a.type==='pc'&&a.name==='Grain'&&a.mode==='ready'&&a.usd===1)));});
