const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),B=require('../planner.js'),S=require('../scenarios.js');
const w='0x'+'2'.repeat(40),other='0x'+'3'.repeat(40),now=Date.parse('2026-10-09T11:00Z');
function harness(){
 const all=[];class Element{constructor(tag){this.tag=tag;this.children=[];this.dataset={};this.style={};this.attrs={};this.events={};this.hidden=false;this._text='';all.push(this);}append(...nodes){for(const n of nodes){this.children.push(n);n.parent=this;}}before(n){const p=this.parent;p.children.splice(p.children.indexOf(this),0,n);n.parent=p;}replaceChildren(...n){this.children=[];this._text='';this.append(...n);}set textContent(s){this._text=String(s??'');this.children=[];}get textContent(){return this._text+this.children.map(n=>n.textContent).join('');}setAttribute(k,v){this.attrs[k]=v;}closest(tag){let p=this;while(p&&p.tag!==tag)p=p.parent;return p;}querySelector(s){return s==='.tabs'?tabs:s==='.footer'?footer:null;}addEventListener(k,f){(this.events[k]??=[]).push(f);}dispatch(k){for(const f of this.events[k]??[])f({preventDefault(){}});}}
 const panel=new Element('panel'),tabs=new Element('tabs'),footer=new Element('footer');panel.append(tabs,footer);
 let clock=now,data={settings:{wallet:w,language:'en'},games:{[w]:{seenAt:now,energyHours:24}},sequence:1},calls=[],writes=[];
 const funding=d=>d.syncError?{error:d.syncError}:{wallet:100,claimable:50,total:150,usd:1.5,hourly:10};
 const plan=(d,o,t)=>{calls.push({sequence:d.sequence,at:t,options:o,wallet:d.settings.wallet});if(d.syncError)return{error:d.syncError,options:o,plans:[]};const p=S.find(o.scenario);return{asOf:d.games[d.settings.wallet].seenAt,computedAt:t,options:o,funding:funding(d),examined:1,baselineHash:10,payout:.95,price:.01,scenario:{id:p.id,days:p.days,heldFraction:.5,milestones:[{day:0,priceUSD:.01,externalHash:1000,budgetCRH:10000,ranked:10},{day:p.days,priceUSD:.01,externalHash:1500,budgetCRH:9000,ranked:12}]},plans:[{capital:5,actions:[{type:'plot',level:2,atDay:0,readyDay:.1,usd:5,tokens:500,fundsAfterCRH:200,reserveUSD:1}],estimate:{endUSD:200,endTokens:20000,hash:10,runningWatts:50,score:100,operating:1,gasETH:0,gasUSD:0,earnedCRH:15000,energyHours:12,pausedHours:0,careShortfallUSD:0}}]};};
 const sandbox={CRHMonitor:{cleanSettings:s=>s},CRHPlanner:{REVISION:B.REVISION,options:B.options,plan},CRHScenarios:S,CRHReinvest:{funding},CRHI18n:{language:s=>s.language,usd:n=>Number.isFinite(n)?'$'+n.toFixed(2):'—',fmt:n=>Number.isFinite(n)?String(n):'—',locale:()=> 'en-US'},Date:class extends Date{static now(){return clock}},document:{createElement:tag=>new Element(tag)},structuredClone,setTimeout,chrome:{storage:{local:{get:async keys=>Object.fromEntries(keys.map(k=>[k,data[k]])),set:async x=>{writes.push(x);Object.assign(data,x);view.render(data);}}}}};
 vm.createContext(sandbox);vm.runInContext(fs.readFileSync(path.join(__dirname,'../planner-view.js'),'utf8'),sandbox);const view=sandbox.CRHPlannerView.attach(panel);view.render(data);
 const input=n=>all.find(e=>e.name===n),form=all.find(e=>e.tag==='form'),output=all.find(e=>e.className==='planner-output'),status=all.find(e=>e.className==='explain planner-status'),submit=form.children.find(e=>e.tag==='button'),compare=form.children.filter(e=>e.tag==='button')[1];
 return{all,input,output,status,calls,writes,get data(){return data},update:x=>{Object.assign(data,x);view.render(data)},advance:ms=>{clock+=ms},render:()=>view.render(data),calculate:()=>form.dispatch('submit'),compare:()=>compare.dispatch('click'),change:(name,value)=>{const e=input(name);if(e.type==='checkbox')e.checked=value;else e.value=value;e.dispatch('change')},open:()=>all.find(e=>e.dataset.tab==='planner').dispatch('click'),idle:async()=>{for(let i=0;i<100;i++){if(!submit.disabled)return;await new Promise(r=>setTimeout(r,5))}throw Error('Calculation did not finish')},remount:()=>{const p=new Element('panel');p.append(tabs,footer);const v=sandbox.CRHPlannerView.attach(p);v.render(data);return all.filter(e=>e.className==='planner-output').at(-1)}};
}
test('successful plan and open action details survive sync gaps and repeated game observations',async()=>{const h=harness();h.calculate();await h.idle();const children=[...h.output.children],detail=h.all.find(e=>e.tag==='details'&&e.textContent.includes('Action order'));assert(detail);assert(detail.open);h.update({syncError:'funding-sync'});assert.deepEqual(h.output.children,children);assert(detail.open);assert.match(h.status.textContent,/cannot currently be used/);h.advance(10*60000);h.update({syncError:null,games:{[w]:{seenAt:now+600000,energyHours:20}}});h.render();await h.idle();assert.equal(h.calls.length,1);assert.deepEqual(h.output.children,children);assert.match(h.status.textContent,/New data/);});
test('failed manual retry retains the good result; successful retry updates it',async()=>{const h=harness();h.calculate();await h.idle();const before=[...h.output.children];h.update({syncError:'fresh-data'});h.calculate();await h.idle();assert.deepEqual(h.output.children,before);h.update({syncError:null});h.calculate();await h.idle();assert.notEqual(h.output.children[0],before[0]);assert.equal(h.calls.length,3);});
test('initial sync error remains until a user requests a retry; background data never runs the search',async()=>{const h=harness();h.update({syncError:'funding-sync'});h.open();await h.idle();assert.match(h.output.textContent,/do not reconcile/);h.advance(600000);h.update({syncError:null});await h.idle();assert.equal(h.calls.length,1);h.calculate();await h.idle();assert.match(h.output.textContent,/Action order/);});
test('four comparisons use one immutable snapshot even when storage changes between variants',async()=>{const h=harness();h.compare();await new Promise(r=>setTimeout(r,80));h.update({sequence:2,games:{[w]:{seenAt:now+1000,energyHours:24}}});await h.idle();assert.equal(h.calls.length,4);assert(h.calls.every(c=>c.sequence===1&&c.at===now));assert.match(h.output.textContent,/Horizons differ/);});
test('wallet and option changes clear results and cannot finish an old-wallet calculation',async()=>{const h=harness();h.compare();await h.idle();assert.match(h.output.textContent,/All 4 scenarios/);h.update({settings:{wallet:other,language:'en'},games:{[w]:{seenAt:now},[other]:{seenAt:now,energyHours:24}}});assert.equal(h.output.textContent,'');h.calculate();h.change('scenario','launch');await h.idle();assert.equal(h.output.textContent,'');h.calculate();await h.idle();assert(!h.output.textContent.includes('All 4 scenarios'));assert.equal(h.calls.at(-1).wallet,other);});
test('saved plans restore only for the matching wallet and options, as historical results',async()=>{const h=harness();h.calculate();await h.idle();const f=h.data.plannerForecasts[w];assert.equal(f.format,'crh-planner-forecast-v2');assert.equal(f.baselineHash,10);assert.equal(f.plans[0].capital,5);const restored=h.remount();assert.match(restored.textContent,/Action order/);const statuses=h.all.filter(e=>e.className==='explain planner-status');assert.match(statuses.at(-1).textContent,/Saved plan restored/);h.update({settings:{wallet:other,language:'en'},games:{[other]:{seenAt:now,energyHours:24}}});assert.equal(h.output.textContent,'');});

test('an earlier-model saved plan stays readable but is explicitly marked for recalculation',async()=>{const h=harness();h.calculate();await h.idle();assert.equal(h.data.plannerForecasts[w].revision,B.REVISION);delete h.data.plannerForecasts[w].revision;const out=h.remount();assert.match(out.textContent,/Action order/);assert.match(h.all.filter(e=>e.className==='explain planner-status').at(-1).textContent,/earlier model/);});

test('the headline uses the same net ending value used to rank plans and component lists separate cash purchases from storage',async()=>{const h=harness();h.calculate();await h.idle();const f=h.data.plannerForecasts[w],p=f.plans[0],part=(id,kind,usd)=>({id,kind,name:id,usd,quantity:1});p.estimate.endUSD=200;p.estimate.liquidUSD=180;p.actions=[{type:'pc',mode:'parts',name:'Upgrade',replace:'setup_1',usd:85,tokens:8500,atDay:0,readyDay:0,fundsAfterCRH:100,reserveUSD:1,recipe:[part('new GPU','gpu',80),part('new PSU','psu',5),part('CPU','cpu',1)],purchasedParts:[part('new GPU','gpu',80),part('new PSU','psu',5)],reusedParts:[part('CPU','cpu',1)],storedParts:[part('old GPU','gpu',9),part('old PSU','psu',1)]}];const out=h.remount();assert.equal(h.all.filter(e=>e.className==='plan-value').at(-1).textContent,'$180.00');assert.match(out.textContent,/Buy these parts/);assert.match(out.textContent,/Already owned — reuse/);assert.match(out.textContent,/Removed parts stay in inventory/);assert.match(out.textContent,/No automatic sale/);assert.match(out.textContent,/CRH value before selling fee and gas/);});
