const test=require('node:test'),assert=require('node:assert/strict'),C=require('../shared.js'),B=require('../planner.js'),R=require('../reinvest-planner.js');
const now=Date.now(),w='0x'+'2'.repeat(40),q=n=>BigInt(Math.round(n*1e6))*10n**12n+'',id=n=>'0x'+n.toString(16).padStart(64,'0');
function fixture(){
 const parts=[{id:'cpu1',kind:'cpu',name:'CPU',usd:1,quantity:1},{id:'gpu1',kind:'gpu',name:'GPU',usd:5,quantity:1},{id:'case1',kind:'case',name:'Case',usd:1,quantity:1}],card={id:'seed',name:'Seed',hash:10,usd:25,watts:50,minHall:1,limit:1,includedHours:24,recipe:parts};
 const level=(level,extra={})=>({level,minutes:15,baseUSD:2,perHashUSD:.01,minHall:1,minPlots:1,bonusPct:0,hashCap:200,capacityW:null,...extra});
 const game={wallet:w,seenAt:now,serverNow:now,settledAt:now,priceUSD:.01,priceQuotable:true,rateConfirmed:true,settlement:'ready',myHash:10,totalHash:1000,hourlyWei:q(25),claimableWei:q(0),claimedWei:q(0),powerLevel:0,gridCapacity:60,gridReserved:50,energyHours:24,energyKwh:1.2,electricityUSD:.55,watts:50,hall:1,openPlots:1,hashRecord:10,packageLimits:[{id:'seed',owned:1,max:1}],pcs:[{id:'setup_1',ready:true,running:true,hash:10,healthyHash:10,watts:50,thermalLossPct:0,wearLossPct:0}],items:parts.map((p,i)=>({id:'part'+i,catalog:p.id,installedSetup:'setup_1'})),dayEnd:now+86400000,budgetWei:q(60000),construction:{plots:[level(1),level(2),level(3,{minHall:2})],hall:[level(1),level(2,{minPlots:2,bonusPct:6})],power:[level(0,{capacityW:60}),level(1,{capacityW:150})]}};
 const records=[{id:id(1),wallet:w,type:'buy',quantityWei:q(2600),direction:1,totalUSD:26,gasWei:q(.000001),gasUSD:.002,block:1,at:now-60000},{id:id(2),wallet:w,type:'game',quantityWei:q(2500),direction:-1,totalUSD:25,gasWei:q(.000001),gasUSD:.002,block:2,at:now-50000}];
 return{settings:{...C.defaults(),wallet:w,language:'en',positions:{}},games:{[w]:game},market:game,chain:{wallet:w,at:now,balanceWei:q(100),ethWei:q(.01),error:null},ledgers:{[w]:{wallet:w,complete:true,at:now,status:'ready',records}},project:{catalog:{seenAt:now,cards:[card]}}};
}
const run=(d,options={})=>B.plan(d,{mode:'reinvest',days:5,hashDailyPct:0,budgetDailyPct:0,priceEndPct:0,...options},now);
function funded(d,walletTokens=100,claimable=0){d.chain.balanceWei=q(walletTokens);d.ledgers[w].records[0].quantityWei=q(walletTokens+2500);d.games[w].claimableWei=q(claimable);return d;}
test('reinvest funding adds only the selected wallet and unclaimed rewards; legacy credits are ignored',()=>{const d=funded(fixture(),100,20);d.games[w].credits_micro=999999999;assert.equal(R.funding(d,now).total,120);assert.equal(R.funding(d,now,false).total,20);d.chain.wallet='0x'+'3'.repeat(40);assert.equal(R.funding(d,now).error,'funding-stale');});
test('pending claims, mismatched balances, stale scans and blocked claims cannot create funds twice',()=>{for(const mutate of [d=>d.chain.balanceWei=q(999),d=>d.ledgers[w].at=now-180001,d=>d.games[w].claimBlocked=true,d=>{d.ledgers[w].records.push({id:id(3),wallet:w,type:'reward',direction:1,quantityWei:q(10),totalUSD:0,gasWei:'0',gasUSD:0,block:3,at:now+1});d.chain.balanceWei=q(110)}]){const d=fixture();mutate(d);assert(R.funding(d,now).error);}const d=fixture();d.chain.at=now-180001;assert.equal(R.funding(d,now).error,'funding-stale');});
test('future mining finances sequential development; the manual budget is ignored and no tokens are borrowed',()=>{const d=fixture(),r=run(d,{budget:1000000});assert(!r.error,r.error);assert(r.plans[0].actions.some(a=>a.type==='pc'));assert(r.plans[0].actions.some(a=>a.atDay>0));for(const p of r.plans){for(const a of p.actions){assert(a.tokens<=a.fundsBeforeCRH+1e-6);assert(a.fundsAfterCRH>=0);if(a.usd>0)assert(Math.abs(a.tokens*a.priceUSD-a.usd)<1e-6);}assert(Math.abs(p.estimate.endTokens-(r.funding.total+p.estimate.earnedCRH-p.spentCRH))<1e-6);assert(p.estimate.gasETH<=r.funding.eth);assert(!p.actions.some(a=>a.type==='pc'&&a.mode==='ready'));}assert(r.plans[0].estimate.hash>10);});
test('no energy and no CRH cannot finance mining from hypothetical future rewards',()=>{const d=funded(fixture(),0,0);d.games[w].energyKwh=0;d.games[w].energyHours=0;const r=run(d);assert(!r.error);assert.equal(r.plans[0].estimate.earnedCRH,0);assert(!r.plans.some(p=>p.actions.some(a=>a.usd>0)));});
test('reinvest can start with zero wallet tokens using accrued rewards and stored energy',()=>{const d=funded(fixture(),0,2000),r=run(d,{includeWallet:false});assert(!r.error);assert.equal(r.funding.wallet,0);assert(r.plans.some(p=>p.actions.some(a=>a.type==='pc')));assert(r.plans[0].estimate.claims>0);});
test('price scenarios affect CRH payment amounts; game payments do not incur a sale fee',()=>{const d=funded(fixture(),100,3000);const high=run(d,{priceEndPct:50}),low=run(d,{priceEndPct:-50});assert(!high.error&&!low.error);assert.equal(high.endPrice,.015);assert.equal(low.endPrice,.005);for(const r of [high,low])for(const p of r.plans)for(const a of p.actions)if(a.usd>0)assert(Math.abs(a.tokens-a.usd/a.priceUSD)<1e-6);d.settings.positions[w]={sellFeePct:99};const fee=run(d);for(const p of fee.plans)for(const a of p.actions)if(a.usd>0)assert(Math.abs(a.tokens-a.usd/.01)<1e-6);});
test('paid builder queue completes automatically and gates buying without an invented extra charge',()=>{const d=funded(fixture(),5000);d.games[w].builderQueueEnd=now+7200000;d.games[w].builderJobs=[{kind:'plot',target:1,endsAt:now+3600000},{kind:'grid',target:1,endsAt:now+7200000}];const r=run(d);assert(!r.error);for(const p of r.plans){assert(!p.actions.some(a=>a.type==='plot'&&a.level===2));assert(!p.actions.some(a=>a.type==='power'&&a.level===1));for(const a of p.actions.filter(a=>a.type==='pc'&&!a.replace))assert(a.atDay*24>=2-1e-7);}assert(r.plans.some(p=>p.actions.some(a=>a.type==='pc')));});
test('reward budget remains today’s until the observed game-day reset',()=>{const d=funded(fixture(),0);d.games[w].energyKwh=1000;d.games[w].dayEnd=now+43200000;const r=run(d,{days:1,budgetDailyPct:-50});assert(!r.error);const expected=(60000*.5+30000*.5)*(10*.925)/(990+10*.925);assert(Math.abs(r.baseline.earnedCRH-expected)<1e-6);});
test('native gas cannot be paid by imaginary CRH conversion or external money',()=>{const d=funded(fixture(),1000,5000);d.chain.ethWei='0';const r=run(d);assert(!r.error);assert(!r.plans.some(p=>p.actions.some(a=>a.usd>0)));assert(r.plans.every(p=>p.estimate.gasETH===0));const e=fixture();for(const record of e.ledgers[w].records)record.gasUSD=null;assert.equal(run(e).error,'gas-data');});
test('a non-profitable reinvestment route may retain rewards instead of forcing expansion',()=>{const d=funded(fixture(),2000);d.games[w].budgetWei=q(24);d.games[w].hourlyWei=q(.01);const r=run(d,{days:2});assert(!r.error);assert.equal(r.plans[0].capital,0);assert(!r.plans[0].actions.some(a=>a.type==='pc'));});
test('reinvestment options are bounded and do not change the existing budget default',()=>{const o=B.options({mode:'reinvest',includeWallet:false,reserveHours:999,goal:'hash'});assert.equal(o.mode,'reinvest');assert.equal(o.includeWallet,false);assert.equal(o.reserveHours,72);assert.equal(o.goal,'hash');assert.equal(B.options().mode,'budget');});
test('confirmed zero payout never turns into mathematical gross emission',()=>{const d=fixture();d.games[w].hourlyWei='0';const r=run(d);assert(!r.error);assert.equal(r.baseline.earnedCRH,0);assert(r.plans.every(p=>p.estimate.earnedCRH===0));});
test('reinvest preserves the input and final trace reconciles with post-care balances',()=>{const d=fixture(),before=JSON.stringify(d),r=run(d);assert(!r.error);assert.equal(JSON.stringify(d),before);for(const p of r.plans){const last=p.trace.at(-1);assert(Math.abs(last.availableCRH-p.estimate.endTokens)<1e-6);assert.equal(last.day,5);assert(p.trace.every(t=>t.availableCRH>=0));}});
test('a free inventory build consumes components once and operating reserve still includes care',()=>{const d=funded(fixture(),1000);d.games[w].openPlots=2;d.games[w].powerLevel=1;d.games[w].gridCapacity=150;for(const part of d.project.catalog.cards[0].recipe)d.games[w].items.push({id:'spare_'+part.id,catalog:part.id,installedSetup:null});const r=run(d,{goal:'hash'});assert(!r.error);assert(r.plans.some(p=>p.actions.some(a=>a.type==='pc'&&a.usd===0)));for(const p of r.plans)assert(p.actions.filter(a=>a.type==='pc'&&a.usd===0).length<=1);for(const p of r.plans)for(const a of p.actions)if(a.type==='pc')assert(a.reserveUSD>0);});
test('hash objective searches for more development while all payments remain self-funded',()=>{const d=funded(fixture(),100,1000),cash=run(d),growth=run(d,{goal:'hash'});assert(!cash.error&&!growth.error);assert(growth.plans[0].estimate.hash>=cash.plans[0].estimate.hash);assert(growth.plans[0].estimate.safe);for(const a of growth.plans[0].actions)assert(a.tokens<=a.fundsBeforeCRH+1e-6);});
test('an incomplete paid queue is reported instead of inventing completed plots',()=>{const d=fixture();d.games[w].builderQueueEnd=now+86400000;assert.equal(run(d).error,'queue-data');});
test('unknown installed parts do not make maintenance look cheaper; an explicit care reserve can unlock it',()=>{const d=fixture();d.games[w].items.push({id:'customBoard',catalog:'unobservedBoard',installedSetup:'setup_1'});assert.equal(run(d).error,'care-unknown');d.settings.positions[w]={careDailyUSD:1};assert(!run(d).error);});
test('a stored tower behind an active sealed setup does not increase maintenance or provide free inventory',()=>{const d=fixture();d.games[w].pcs[0].slots={cpu:'part0',gpu:'part1',case:'part2'};d.games[w].items.push({id:'storedTowerPart',catalog:'unobservedPart',installedSetup:'setup_1'});const r=run(d);assert(!r.error);});
// Component removal is an inventory transfer; it never provides cash for a replacement.
test('GPU + PSU replacement charges new parts in full and retains removed hardware for later reuse',()=>{const part=(id,kind,usd,quantity=1)=>({id,kind,name:id,usd,quantity}),base=[part('case','case',1),part('cpu','cpu',1),part('ram','ram',.25,4)],old=[...base,part('oldGPU','gpu',9),part('oldPSU','psu',1)],recipe=[...base,part('newGPU','gpu',80),part('newPSU','psu',5)],flow=B.componentFlow({},old,recipe,'parts');assert.equal(flow.partsCostUSD,85);assert.deepEqual(flow.purchasedParts.map(p=>p.id),['newGPU','newPSU']);assert.equal(flow.reusedParts.find(p=>p.id==='ram').quantity,4);assert.deepEqual(flow.storedParts.map(p=>p.id),['oldGPU','oldPSU']);assert.equal(flow.inventory.oldGPU,1);assert.equal(flow.inventory.oldPSU,1);const later=B.componentFlow(flow.inventory,[],old,'parts');assert.equal(later.partsCostUSD,3);assert(!later.purchasedParts.some(p=>['oldGPU','oldPSU'].includes(p.id)));assert.equal(later.inventory.oldGPU,0);assert.equal(later.inventory.oldPSU,0);});
test('ready-card replacement keeps the entire old build and consumes no inventory components',()=>{const old=[{id:'old',kind:'gpu',name:'Old GPU',usd:9,quantity:1}],recipe=[{id:'new',kind:'gpu',name:'New GPU',usd:80,quantity:1}],inventory={new:1},flow=B.componentFlow(inventory,old,recipe,'ready');assert.equal(flow.inventory.new,1);assert.equal(flow.inventory.old,1);assert.equal(flow.reusedParts.length,0);assert.equal(flow.storedParts.length,1);assert.equal(flow.purchasedParts.length,1);assert.deepEqual(inventory,{new:1});});
test('forecast wear is applied equally to existing and new PCs instead of favoring existing hardware',()=>{const d=funded(fixture(),10000);d.games[w].openPlots=2;d.games[w].powerLevel=1;d.games[w].gridCapacity=150;const r=run(d,{goal:'hash'});assert(!r.error);assert.equal(r.baseline.hash,9.25);for(const p of r.plans)for(const pc of p.pcs)assert(Math.abs(pc.hash-pc.healthy*.925)<1e-10);assert.equal(d.games[w].pcs[0].hash,10);});
test('mixed and expansion routes receive independent search budgets and the best survives the merge',()=>{const r=run(funded(fixture(),100,1000));assert(!r.error);assert.deepEqual(r.searches.map(x=>x.policy),['mixed','expansion']);assert.equal(r.examined,r.searches.reduce((n,x)=>n+x.examined,0));assert(r.examined<=36000);assert(Math.abs(r.plans[0].estimate.liquidUSD-Math.max(...r.searches.map(x=>x.bestLiquidUSD)))<1e-6);for(const p of r.plans.filter(p=>p.searchPolicy==='expansion'))assert(!p.actions.some(a=>a.type==='pc'&&a.replace));});

test('rounded card hashrate does not invent a free refresh upgrade of the same components',()=>{const d=funded(fixture(),10000);d.games[w].pcs[0].healthyHash=9.9998;d.games[w].pcs[0].hash=9.9998;d.games[w].myHash=9.9998;const r=run(d);assert(!r.error);assert(!r.plans.some(p=>p.actions.some(a=>a.type==='pc'&&a.replace==='setup_1')));for(const p of r.plans)for(const pc of p.pcs)assert.equal(pc.healthy,9.9998);});
test('sealed systems are bought as cards; missing sealed boxes are not treated as freely repeatable shop parts',()=>{const d=funded(fixture(),10000),grain={id:'grain',name:'Grain',hash:.25,usd:1,watts:5,minHall:1,limit:1,includedHours:24,recipe:[{id:'system_grain',name:'Grain',kind:'system',usd:1,quantity:1}]};d.project.catalog.cards.push(grain);d.games[w].packageLimits.push({id:'grain',owned:0,max:1});const r=run(d,{goal:'hash'});assert(!r.error);assert(!r.plans.some(p=>p.actions.some(a=>a.type==='pc'&&a.name==='Grain'&&a.mode==='parts'&&a.purchasedParts.length)));for(const p of r.plans)assert(p.actions.filter(a=>a.type==='pc'&&a.name==='Grain'&&a.mode==='ready').length<=1);});

function expansionCase(){const d=funded(fixture(),10400),g=d.games[w],cards=require('./catalog-rules-20261009.json');d.project.catalog.cards=cards;g.pcs=[];g.items=[];for(const [index,name]of ['sprout','seed','seed','seed','seed'].entries()){const card=cards.find(c=>c.id===name),setup='setup_'+(index+1);g.pcs.push({id:setup,ready:true,running:true,hash:card.hash,healthyHash:card.hash,watts:card.watts,thermalLossPct:0,wearLossPct:0});for(const p of card.recipe)for(let n=0;n<p.quantity;n++)g.items.push({id:'fixture_'+g.items.length,catalog:p.id,installedSetup:setup});}const healthy=g.pcs.reduce((n,p)=>n+p.hash,0);g.myHash=healthy*1.45;g.totalHash=50000;g.priceUSD=.0025;g.hourlyWei=q(60000000*g.myHash/g.totalHash*.95/24);g.budgetWei=q(60000000);g.hall=6;g.openPlots=5;g.powerLevel=2;g.gridCapacity=575;g.gridReserved=411;g.watts=411;g.hashRecord=healthy;g.energyKwh=7.7;g.energyHours=g.energyKwh*1000/411;g.packageLimits=cards.filter(c=>c.limit!==null).map(c=>({id:c.id,owned:['seed','sprout'].includes(c.id)?1:0,max:c.limit}));g.builderQueueEnd=now+4.85*3600000;g.builderJobs=[{kind:'plot',target:5,endsAt:g.builderQueueEnd}];g.dayEnd=now+2.45*3600000;g.rateBps=1000;g.rateChange={rateBps:1200,startsAt:g.dayEnd};g.releasedWei=q(60000000*(1-2.45/24));g.construction=require('./construction-rules-20261009.json');return d;}

test('multi-step island expansion is retained when the general beam prunes a better construction chain',()=>{const d=expansionCase(),before=JSON.stringify(d),r=B.plan(d,{mode:'reinvest',scenario:'slow',launchAt:now+2.45*3600000,reserveHours:72,goal:'balance'},now);assert(!r.error);const mixed=r.searches.find(x=>x.policy==='mixed'),expansion=r.searches.find(x=>x.policy==='expansion');assert(mixed.truncated);assert(expansion.bestLiquidUSD>mixed.bestLiquidUSD+20);assert.equal(r.plans[0].searchPolicy,'expansion');const p=r.plans[0];assert.equal(p.pcs.length,8);assert.equal(p.hall,11);assert(Math.abs(p.estimate.hash-p.pcs.reduce((n,pc)=>n+pc.hash,0)*1.84)<1e-6);assert(Math.abs(p.estimate.endTokens-(r.funding.total+p.estimate.earnedCRH-p.spentCRH))<1e-6);assert.equal(JSON.stringify(d),before);});
