const test=require('node:test'),assert=require('node:assert/strict'),C=require('../shared.js'),B=require('../planner.js'),R=require('../reinvest-planner.js');
const now=Date.parse('2026-10-09T11:00:00Z'),w='0x'+'2'.repeat(40),q=n=>BigInt(Math.round(n*1e6))*10n**12n+'',id=n=>'0x'+n.toString(16).padStart(64,'0');
function fixture(){
 const parts=[{id:'cpu1',kind:'cpu',name:'CPU',usd:1,quantity:1},{id:'gpu1',kind:'gpu',name:'GPU',usd:5,quantity:1},{id:'case1',kind:'case',name:'Case',usd:1,quantity:1}],card={id:'seed',name:'Seed',hash:10,usd:25,watts:50,minHall:1,limit:1,includedHours:24,recipe:parts};
 const level=(level,extra={})=>({level,minutes:15,baseUSD:2,perHashUSD:.01,minHall:1,minPlots:1,bonusPct:0,hashCap:200,capacityW:null,...extra});
 const game={wallet:w,seenAt:now,serverNow:now,settledAt:now,priceUSD:.01,priceQuotable:true,rateConfirmed:true,settlement:'ready',myHash:10,totalHash:1000,hourlyWei:q(25),claimableWei:q(0),claimedWei:q(0),powerLevel:0,gridCapacity:60,gridReserved:50,energyHours:24,energyKwh:1.2,electricityUSD:.55,watts:50,hall:1,openPlots:1,hashRecord:10,packageLimits:[{id:'seed',owned:1,max:1}],pcs:[{id:'setup_1',ready:true,running:true,hash:10,healthyHash:10,watts:50,thermalLossPct:0,wearLossPct:0}],items:parts.map((p,i)=>({id:'part'+i,catalog:p.id,installedSetup:'setup_1'})),dayEnd:now+5*3600000,rateBps:1000,rateChange:{rateBps:1200,startsAt:now+5*3600000},releasedWei:q(60000*19/24),budgetWei:q(60000),construction:{plots:[level(1),level(2),level(3,{minHall:2})],hall:[level(1),level(2,{minPlots:2,bonusPct:6})],power:[level(0,{capacityW:60}),level(1,{capacityW:150})]}};
 const records=[{id:id(1),wallet:w,type:'buy',quantityWei:q(2600),direction:1,totalUSD:26,gasWei:q(.000001),gasUSD:.002,block:1,at:now-60000},{id:id(2),wallet:w,type:'game',quantityWei:q(2500),direction:-1,totalUSD:25,gasWei:q(.000001),gasUSD:.002,block:2,at:now-50000}];
 return{settings:{...C.defaults(),wallet:w,language:'en',positions:{}},games:{[w]:game},market:game,chain:{wallet:w,at:now,balanceWei:q(100),ethWei:q(.01),error:null},ledgers:{[w]:{wallet:w,complete:true,at:now,status:'ready',records}},project:{catalog:{seenAt:now,cards:[card]}}};
}

const S=require('../scenarios.js');
const run=(d,scenario='slow',extra={})=>B.plan(d,{mode:'reinvest',scenario,...extra},now);
test('four named presets replace manual percentages and keep the public launch fixed',()=>{assert.deepEqual(S.presets.map(p=>p.days),[3,5,7,10]);const o=B.options({scenario:'hype',days:1,priceEndPct:-90});assert.equal(o.days,10);assert.equal(o.launchAt,S.LAUNCH);const d=fixture(),a=S.compile(d,o,now),b=S.compile(d,o,now+3600000);assert.equal(a.meta.launchAt,b.meta.launchAt);assert(Math.abs(a.meta.launchDay*24-5)<1e-8);assert(Math.abs(b.meta.launchDay*24-4)<1e-8);assert.equal(a.priceAt(0),.01);assert.equal(a.externalAt(0),990);});
test('today budget stays fixed and the announced 12 percent starts exactly at reset',()=>{const d=fixture(),a=S.compile(d,B.options({scenario:'slow'}),now),t=5/24;assert.equal(a.at(t-1e-6).budgetCRH,60000);assert.equal(a.meta.rateNext,.12);assert(a.at(t).budgetCRH>60000*.9*.12/.1);assert(Math.abs(a.at(t).budgetCRH-a.at(t).poolCRH*.12)<1e-8);assert.equal(a.at(t+.1).budgetCRH,a.at(t).budgetCRH);});
test('vault and claimable liabilities never become the reward pool',()=>{const d=fixture(),o=B.options({scenario:'slow'}),a=S.compile(d,o,now);d.chain.vaultWei=q(999999999);d.games[w].claimableWei=q(5000000);const b=S.compile(d,o,now);assert.deepEqual(a.rows,b.rows);assert.equal(a.meta.initialPool,600000-60000*19/24);});
test('measured top-spend growth is a lower bound and only eligible at the next day',()=>{const d=fixture(),id='isl_'+'a'.repeat(20),board=(at,tokens)=>({board:'spend',complete:true,stale:false,query:'',page:1,ranked:1,total:1,asOf:at,seenAt:at,rows:[{id,spentTokens:tokens}]});d.project.boards={spend:[board(now-3600000,100),board(now,1100)]};const a=S.compile(d,B.options({scenario:'slow'}),now),plain=S.compile(fixture(),B.options({scenario:'slow'}),now);assert.equal(a.meta.knownPurchaseLowerBoundCRH,1000);assert.equal(a.at(0).budgetCRH,plain.at(0).budgetCRH);assert(Math.abs(a.at(5/24).budgetCRH-plain.at(5/24).budgetCRH-72)<1e-7);d.project.boards.spend[1].query='search';assert.equal(S.knownInflows(d,d.games[w],now).tokens,0);});
test('a price pump is not inferred from spending preheld tokens; volatile bounds include interior peaks',()=>{const d=fixture(),a=S.compile(d,B.options({scenario:'launch'}),now),h=S.compile(d,B.options({scenario:'hype'}),now);assert.equal(a.meta.heldFraction,.8);assert(a.at(3).externalHash>990*4);assert(a.priceAt(3)<.01);assert(h.maximum.price>h.priceAt(0)&&h.maximum.price>h.priceAt(10));assert(h.maximum.budget>=Math.max(...h.rows.map(p=>p.budgetCRH)));});
test('pool replenishment follows game purchases, burn and treasury never fund players',()=>{const d=fixture();d.games[w].poolWei=q(100000);const a=S.compile(d,B.options({scenario:'slow'}),now);let pool=100000,pending=0,budget=60000;for(let i=1;i<a.rows.length;i++){const x=a.rows[i-1],y=a.rows[i],mid=(x.day+y.day)/2,spend=y.spendUSD-x.spendUSD;pending+=spend/a.priceAt(mid)*.6;pool=Math.max(0,pool-budget*(y.day-x.day));if(a.resets.some(t=>Math.abs(t-y.day)<1e-8)){pool+=pending;pending=0;budget=pool*a.rateAt(y.day);}assert(Math.abs(y.poolCRH-pool)<1e-5);assert(Math.abs(y.budgetCRH-budget)<1e-5);}});
test('scenario reinvestment conserves tokens, respects inventory and records the chosen model',()=>{const d=fixture(),before=JSON.stringify(d),r=run(d);assert(!r.error,r.error);assert.equal(r.scenario.id,'slow');assert.equal(r.options.days,5);assert.equal(JSON.stringify(d),before);for(const p of r.plans){assert(Math.abs(p.estimate.endTokens-(r.funding.total+p.earnedCRH-p.spentCRH-p.soldCRH))<1e-6);for(const a of p.actions){assert(a.tokens<=a.fundsBeforeCRH+1e-6);assert(Math.abs(a.tokens*a.priceUSD-a.usd)<1e-6);}assert(p.trace.every(t=>t.budgetCRH>0&&t.totalHash>=t.hash));}});
test('collapse forbids capital purchases, models early sales and cannot spend exit proceeds',()=>{const r=run(fixture(),'death');assert(!r.error);const p=r.plans[0];assert.equal(p.capital,0);assert.equal(p.actions.length,0);assert(p.exits.length>0);assert(p.exits.every(e=>e.atDay<=2.5));assert.equal(p.estimate.hash,0);assert.equal(p.estimate.endUSD,p.cashUSD);assert(Math.abs(p.estimate.endTokens-(r.funding.total+p.earnedCRH-p.spentCRH-p.soldCRH))<1e-6);assert(Math.abs(p.cashUSD-p.exits.reduce((n,e)=>n+e.usd,0))<1e-6);});
test('missing exit gas does not fabricate dollar proceeds or a guaranteed sale',()=>{const d=fixture();d.chain.ethWei='0';const r=run(d,'death');assert(!r.error);assert.equal(r.plans[0].cashUSD,0);assert.equal(r.plans[0].estimate.endUSD,0);});
test('numbered RAM and fan slots survive sanitization',()=>{const g=fixture().games[w];g.pcs[0].slots={cpu:'part0',ram_0:'ram0',fan_1:'fan1',secret:'no'};const out=C.validateSnapshot(g);assert.equal(out.pcs[0].slots.ram_0,'ram0');assert.equal(out.pcs[0].slots.fan_1,'fan1');assert.equal(out.pcs[0].slots.secret,undefined);});
test('installed RAM and fans with omitted slot IDs still count toward care and replacement inventory',()=>{const d=fixture(),parts=d.project.catalog.cards[0].recipe;parts.push({id:'ram1',kind:'ram',name:'RAM',usd:1,quantity:1},{id:'fan1',kind:'fan',name:'Fan',usd:1,quantity:1});d.games[w].pcs[0].slots={cpu:'part0',gpu:'part1',case:'part2'};d.games[w].items.push({id:'ramPart',catalog:'ram1',installedSetup:'setup_1'},{id:'fanPart',catalog:'fan1',installedSetup:'setup_1'});d.games[w].energyKwh=10000;d.chain.balanceWei=q(1000000);d.ledgers[w].records[0].quantityWei=q(1002500);const r=B.plan(d,{mode:'reinvest',days:1,hashDailyPct:0,budgetDailyPct:0},now);assert(!r.error);assert(r.baseline.operating>.30);});

test('refreshes after launch do not restart the public-launch shock',()=>{const d=fixture(),o=B.options({scenario:'launch'}),after=now+29*3600000,a=S.compile(d,o,after);assert.equal(a.meta.launchAt,S.LAUNCH);assert.equal(a.externalAt(0),990);assert(a.externalAt(1)<990*2);assert(a.priceAt(0)===.01);});

test('your modeled payments replenish next-day rewards without changing today emission',()=>{const d=fixture();d.chain.balanceWei=q(5000);d.ledgers[w].records[0].quantityWei=q(7500);const r=run(d),market=S.compile(d,r.options,now),p=r.plans[0];assert(!r.error);assert(p.spentCRH>0);assert(p.trace.filter(x=>x.day<5/24-1e-8).every(x=>x.budgetCRH===60000));assert(p.trace.some(x=>x.day>5/24&&x.budgetCRH>market.at(x.day).budgetCRH));assert(p.ownPool+p.poolPending<=p.spentCRH*.6+1e-6);});
